### PR TITLE
Add compatibility with emonpi and flexible sending of data via MQTT

### PR DESCRIPTION
**Pull request by alandpearson**
This feature adds the ability of emonGLCD to work with emonpi, and for the emonGLCD to receive data via MQTT.

It allows to select any node/input variable in emonpi and send them to multiple emonGLCDs for display using MQTT (script provided to do so)
It also makes minor improvements to the codebase, for example checking RF data received length and if the RF data is for itself. 

The emonGLCD is a great device and I'm saddened to hear it's discontinued. Maybe this code update will make it live again ?

### CODE REVIEW

**Comment by glynhudson** [comment]
Great, thanks for this. I also liked the emonGLCD. The main issue was that it was difficult to manufacture pre-assembled at a reasonable price. Most users don't want to build up the kit. We still have kits left in stock which we're struggling to sell: https://openenergymonitor.com/sale-emonglcd-lcd-display-unit-kit/

**Comment by alandpearson** [comment]
Thats real shame. The unit absolutely rocks. It's a lot better in person than in the pics on the site too. 

I'd really really hate to see it discontinued, as it really fills a niche. Maybe there is a way to make a SMD version that would save a lot of assembly, leaving only the display to solder on ?

I bought three of the things I was so impressed...

**Comment by glynhudson** [comment]
That was the main issue that making an SMD version was going to be tricky and hard to do in a cost-effective way. Especially since a proper injection moulded enclosure would be required to give the unit proper protection to obtain CE mark. The injection moulding process was going to require a significant upfront investment. The feedback we got was the most users would prefer to use a smartphone or tablet. We may revisit it, maybe a 3D printed enclosure could work for a small batch run.

**Comment by alandpearson** [comment]
So what I meant was the PCB could be all SMD and completed. I think I understand what you mean, to sell as a completed product requires all of the above to get CE.  That's such a shame.
I don't know how to avoid all of that, I just know it's an awesome little product and something that could be bundled with the emonpi itself - as the complete monitoring solution.

Also, locating and loading the firmware on these devices is a huge blocker. You have tinkerers who don't have all the kit to flash an arduino, nor will to do so. But they are quite cable to solder something together...  

Sorry I just love the device in it's current form (apart from the hour required to solder it together ;) )

PS, if you could update the shop page to say it is now compatible with the emonpi that may help !

**Comment by glynhudson** [comment]
>PS, if you could update the shop page to say it is now compatible with the emonpi that may help !

That's a good idea. So all a user has to do is to add the following to emohub.conf to send emonPi data to the emonGLCD:

```
[[20]]
nodename = emonglcd
firmware =V1_1
hardware = emonglcd
[[[rx]]]
names = temperature,
datacodes = h
scales = 0.01,1
units = c
[[[tx]]]
names=nodeid,hour,minute,second,utilityW,solarW,utilityKwh,solarKwh
datacodes =b,b,b,h,h,H,H
units = h,min,sec,W,W,kwh,kwh
```

And then have some sort of service to post the data to MQTT? How are you doing this? Maybe we could post a nodRED example?

**Comment by alandpearson** [comment]
Exactly !

That's all the user has to do is add the above to the emonhub.conf.

I created a service to do just that (send via MQTT) and is _very_ configurable. It's included in the pull request for this. From the readme 

A companion script (emonglcd-send.pl) has been provided in this repo that reads any emonhub node/feed values and transmits them to mulitple emonglcd(s). 
Simply place the emonglcd-send.cfg file in /etc , edit it with your emonGLCD nodeid(s) and the variables you wish to use for solarW, utilityW, solarKwh and utilityKwh. 
The script will update the emonpi each time any of these node variables change in emonhub. emonglcd-send.pl works by subscribing to these topics via MQTT and using MQTT to make RF transmit requests to emonhub (which are then sent to each emonglcd).

A systemd run file has also been provided to run this at startup, simply place systemd/emonglcd.service into /lib/systemd/system and run 'systemctl enable emonglcd'


I also have some nodered stuff going on to integrate with Alexa ('Alexa open bedroom blinds!') that sends via nodeRed/MQTT node to emonhub which is then transmitted to the jee node.

I'll dig it out.

Personally as someone who had no mqtt/node red experience until a few short months ago, the mosquitto_pub and mosquitto_sub   test programs were invaluable.

**Comment by glynhudson** [comment]
Got it, the updated emonglcd readme explains it well. I still think a nodered flow would be easier for most users.

**Comment by glynhudson** [comment]
Thanks. NodeRED is no longer installed by default on the emonPi. But it's easy to use if required.

**Comment by glynhudson** [comment]
Thanks for your comments, it's really great to hear that you have found the emonPi and nodered useful. I personally pushed to get nodered included on the emonPi, however, it has become apparent that not many users use nodered  / openhab and even fewer users apply security updates. We considered the increased attack vector of having nodered/ openhab running unknown to many users was not worth it. 

At the same time, we have also changed our latest emonSD image to dropping our read-only root file system, so installing NodeRED on the current emonPi is as simple as `sudo apt-get install nodred`. Maybe a hybrid solution of having nodred installed but disabled by default would have been a better solution. This is something we will consider in the future. 

You raise a valid point about the increased complexity of containers. However, containers offer lots of positives for developers and users. I personally think that if we documented the development process and made developing using containers accessible it would bring significant benefits. We did investigate using Debian packaging but for the emonPi we require much granular lower level access. No decision has been made yet, we're still evaluating options. Thanks again for your feedback.

**Pull request merged**
